language: python
sudo: false

deploy:
  provider: pypi
  user: lukassnoek
  password:
    secure: U8Bfe8mXUSp5HYzGsyJfLuVzu+uEt6hid6AQb+HafJMHhhmoiX4cL8IH1xYaT/ZDXR02IO5bpQpjLLvKizDCXrfEgM/YTWhi1lldVh8O6cdP0gBeNfYNQz0qmbWhJFGzN+ad4VXBXrCVIPtF88mmowzRr6P0vLHW8GudSPInJKl6ofUwJDkOOFL6tqAiSLTIlwQQtvKTMqxCAQ3U+kliznpbbjFJSCjf29IQ/tUqzflbKmVdpr5nXCwVONNnydnY8fFK9Vrhl2UchFKjE5KbfoYxFs9udhlgxZMoKSDmTcvhhjwZ7HN8WPABxvY+IvrDi+CUjFDKBKZhSan0fQBfc8aMN0YVE2/TtEJXwsA9g4c3/BkcoF532mc7e2dzExQwOh/xS/iLPhn0qtf+VQn7po7iXwSMbpPIqEOYbgpaWXzgo0Pf5O5Q0pKzuXpcN4femZ1hEtTZ9f13LHuyjLPN9GAZjQmdUGbIkPFY/bbu6ssbkcgKZTABODln68LOnLDQGqpog5bYQ9Myr5mLhF3duLjnoZIcuReyQ7Ed8Z7bcNeiu7t4PAWbgm2DJ3VrUkzq24iUvGedwh3Eqr4eQnedrk2Bn3+rqVv00FjX9elmR7S3TJ4l4jPkfg8R48tDan6wGqhu3s2S97MSmgi+/gWDAEpTBHaHc5DuZ4TcJXTb3To=
  on:
    tags: true
    repo: spinoza-rec/bidsify

env:
  global:
    - PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
  - '2.7'
  - '3.6'

before_install:
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - travis_retry sudo apt-get update -qq
  #- travis_retry sudo apt-get install dcm2niix
  - git clone https://github.com/neurolabusc/dcm2niix
  - mkdir dcm2niix/build
  - cd dcm2niix/build
  - cmake ..
  - make
  - sudo cp bin/dcm2niix /usr/bin
  - travis_retry sudo apt-get install nodejs
  - npm install -g bids-validator

install:
- travis_retry pip install $PIP_DEPS
- cd $TRAVIS_BUILD_DIR
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- python download_test_data.py
- py.test --cov-report term-missing --cov=bidsify

after_success:
- coveralls
